services:
  cad-runner:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cad-runner
    restart: unless-stopped
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "5001:5001"
    expose:
      - "5001"
    networks:
      - cad-net

networks:
  cad-net:
    external: true