version: '3.8'
services:
  cad-runner:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cad-runner
    restart: unless-stopped
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "5001:5001"
    expose:
      - "5001"
    networks:
      - cad-net
  step-parser:
    build: .
    volumes:
      - .:/app
      - ./output:/app/output
    environment:
      - DISPLAY=:99
    command: ["conda", "run", "-n", "step-parser", "python", "testStep.py", "--input_dir", "/app", "--output_dir", "/app/output"]

networks:
  cad-net:
    external: true