services:
  cad-runner:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cad-runner
    restart: unless-stopped
    volumes:
      - .:/app
      # Mount X11 socket for display sharing
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # Mount X11 authentication if it exists
      - /root/.Xauthority:/root/.Xauthority:ro
    working_dir: /app
    network_mode: host
    environment:
      # Set DISPLAY to match your host's DISPLAY
      - DISPLAY=:1
      # Allow X11 connections
      - XAUTHORITY=/root/.Xauthority
    # Add these for X11 access
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE